FROM harbor.k8s.temple.edu/library/ruby:3.4-alpine

WORKDIR /app

COPY . .

USER root

ARG RAILS_MASTER_KEY
ARG RAILS_ENV
ARG BUNDLE_PATH

RUN apk add -U --no-cache \
      bash=5.3.3-r1 \
      libxslt=1.1.43-r3 \
      tzdata=2026a-r0 \
      shared-mime-info=2.4-r6 \
      imagemagick=7.1.2.19-r0 \
      mariadb-connector-c=3.4.6-r0 && \
    apk add -U --no-cache --virtual build-dependencies \
      sudo \
      curl \
      git=2.52.0-r0 \
      build-base=0.5-r3 \
      libxslt-dev=1.1.43-r3 \
      sqlite=3.51.2-r0 \
      sqlite-dev=3.51.2-r0 \
      mariadb-dev=11.4.10-r0 \
      yaml-dev=0.2.5-r2  && \
    gem install bundler:2.3.24 && \
    chmod +x .docker/app/entrypoint-dev.sh

ENTRYPOINT [".docker/app/entrypoint-dev.sh"]
EXPOSE 3000

CMD ["sleep", "infinity"]
