# Place any default configuration for solr_wrapper here
port: 8090
collection:
  dir: solr/conf/
  name: gencon50-1.0
  persist: true
persist: true
instance_dir: tmp/solr/
download_dir: tmp/
version: 8.2.0
