
version: 2

workflows:
  version: 2
  run_tests:
    jobs:
      - run_tests
  qa_deploy:
    jobs:
      - prod_deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/

jobs:
  run_tests:
    docker:
      - image: circleci/ruby:2.6.5-node
        environment:
          TZ: "America/New_York"

      - image: circleci/postgres:11-alpine
        environment:
          TZ: "America/New_York"
          BUNDLER_VERSION: "2.0.1"
    steps:
      - checkout
      - run:
          command: |
            sudo gem update --system
            sudo gem install -f bundler --version "$BUNDLER_VERSION"
            sudo apt-get update
            sudo bundle install
            RAILS_ENV=test sudo bundle exec rake db:setup
            sudo bundle exec rspec spec

  qa_deploy:
    docker:
      - image: circleci/python:3.6.6
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "2c:e8:55:f8:43:47:17:d6:b3:0d:15:23:72:27:13:ad"
            - "2f:37:66:17:11:ae:f9:0f:9e:52:98:41:fe:d0:0c:78"
      - run:
          command: bash .circleci/deploy-qa.sh
