
version: 2

workflows:
  version: 2
  run_tests:
    jobs:
      - run_tests
  deploy:
    jobs:
      - qa_deploy:
          filters:
            branches:
              only:
                - main
      - prod_deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/

jobs:
  run_tests:
    docker:
      - image: cimg/ruby:3.1.3-node
        environment:
          TZ: "America/New_York"

      - image: cimg/postgres:11.12
        environment:
          TZ: "America/New_York"
          BUNDLER_VERSION: "2.3.24"
    steps:
      - checkout
      - run:
          command: |
            gem update --system
            gem install -f bundler --version "$BUNDLER_VERSION"
            sudo apt-get --allow-releaseinfo-change update
            sudo apt-get install sqlite3 libsqlite3-dev
            bundle install
            bundle exec rubocop
            bundle exec brakeman --no-pager --no-threads
            RAILS_ENV=test bundle exec rake db:setup
            echo "bundle exec rspec spec"
            bundle exec rspec spec

  prod_deploy:
    docker:
      - image: cimg/python:3.7.11
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "96:52:81:94:2a:1f:32:82:cd:b5:2d:e3:e3:9e:9d:08"
      - run:
          command: bash .circleci/deploy-prod.sh
          no_output_timeout: 30m

  qa_deploy:
    docker:
      - image: cimg/python:3.7.11
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "96:52:81:94:2a:1f:32:82:cd:b5:2d:e3:e3:9e:9d:08"
      - run:
          command: bash .circleci/deploy-qa.sh
          no_output_timeout: 30m
