development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://localhost:8090/solr/gencon50-v3.0.1.0" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://localhost:8090/solr/gencon50-v3.0.1" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://localhost:8090/solr/gencon50-v3.0.1.0" %>
