development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8090/solr/gencon50" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8090/solr/gencon50" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8090/solr/gencon50" %>
